services:
  web:
    build:
      context: .
      dockerfile: News App/Dockerfile
    depends_on:
      - db
    ports:
      - "3000:80"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: news
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: